### ISSUE TITLE
Fix migrations in prod

### ISSUE THREAD

**Issue by ForsbergPhilip** [Etimo/diamonds2#106]
The migrations does not work in prod. No migrations run in prod atm, probably because no migrations are found. This could be because the project is located in /app/dist instead of /app/src. 

The db tables has been created because we have synchronize set to true in app.module.ts (this should not be set to true in prod). 

If we run the migrations after the tables has been synchronized the migrations will fail because the tables already exists. We cannot run the first two migrations in prod again. 

(1581033024979-init, 1591271803639-seasons)

**Comment by indrif** [comment]
Ah ok so synchronize is only some kind of middle thing for making sure tables exist? Weird behavior, I thought that meant that migrations run upon start. I know it is not recommended but this project is not a critical app with critical uptime requirements. But then we need to make sure migrations run before starting the app, perhaps it can be done in the same way as we do in some other docker compose?

**Comment by indrif** [comment]
We can also add the early migrations to the migration table to say that they have been run, then other migrations will run properly when we have fixed this.

**Comment by ForsbergPhilip** [comment]
The migrations run before app starts today (docker-compose.prod-run). And we can see in the logs in prod that the migrations run, but that no migrations where found. I can add the early migrations to the db and I have started working on a fix for this. Will probably try to release the fix late so we can get all the old season/highscore data.

**Comment by indrif** [comment]
Ok!

**Comment by ForsbergPhilip** [comment]
Fixed.
