### ISSUE TITLE
Autoscale AWS server

### ISSUE THREAD

**Issue by ForsbergPhilip** [Etimo/diamonds2#118]
Scale AWS server during seasons to handle higher load of users.

**Comment by indrif** [comment]
One simple suggestion is to create a shell script that can perform the changes. The things that need to be performed are:
1. Stop server
2. Change instance type (expensive when season, cheap when off-season)
3. Start server

When starting the server the docker container must also be started in some way. Perhaps this can be configured in docker or in the containers?

Then when we have a script we can add it as a cron job or something that checks daily if there is a competition coming up. Then the day before the competition it scales up the server and the day after it ends it scales down again.

**Comment by ForsbergPhilip** [comment]
Working on a script for this.
