### ISSUE TITLE
Auto scale boards

### ISSUE THREAD

**Issue by ForsbergPhilip** [Etimo/diamonds2#119]
Add more boards if a lot of users are playing.

**Comment by ForsbergPhilip** [comment]
Adding middleware so we can add/decrease number of boards depending on the amount of calls to /move endpoint.

Proposal: Default 4 boards.
A user can do 600 moves/minute.

We should have 1 board per 1200 requests.
< 4800 requests = 4 boards.
< 6000 requests = 6 boards.
etc...

**Comment by indrif** [comment]
Interesting idea! 

How do you mean with 1200 requests? 1200 requests / minute or in what time frame?

Skickat från min iPhone
