### ISSUE TITLE
Create slack app with slash command

### ISSUE THREAD

**Issue by ForsbergPhilip** [Etimo/diamonds2#130]
We could create slack slash commands to list information about diamonds.
We could also use this to add new seasons etc.

By doing this we don't have to create a new admin panel, because this will be handled in a slack channel instead.

**Comment by indrif** [comment]
Interesting idea! 

Some initial questions, what are your thoughts about integrating into diamonds? Some private api? Direct connection to dB?

**Comment by ForsbergPhilip** [comment]
Deployed. I have created a new controller for /slack.
