### ISSUE TITLE
Slack command to set rules for new season

### ISSUE THREAD

**Issue by H4zze** [Etimo/diamonds2#210]
To make it easier to use different rules for different seasons an extra modal could be added to set rules a specific season.
The modal can be a sub level of the create season modal.

**This proposal requires the rules to be stored per season. This is currently not supported and will require a back end update as well.**

Add season modal:
![image](https://user-images.githubusercontent.com/21332068/137486771-eb5cbced-a989-460f-b17c-59a845d6b8e8.png)

Select rules modal:
![image](https://user-images.githubusercontent.com/21332068/137486857-f55cb9f4-d089-4353-ac6a-9321b31d18fe.png)

**Comment by H4zze** [comment]
Add season modal code:
`
{
  "view": {
    "type": "modal",
    "submit": {
      "type": "plain_text",
      "text": "Submit"
    },
    "close": {
      "type": "plain_text",
      "text": "Cancel"
    },
    "title": {
      "type": "plain_text",
      "text": "Add season"
    },
    "blocks": [
      {
        "type": "input",
        "block_id": "season_name",
        "element": {
          "type": "plain_text_input",
        },
        "label": {
          "type": "plain_text",
          "text": "Season name"
        }
      },
      {
        "type": "input",
        "block_id": "start_date",
        "element": {
          "type": "datepicker",
          "placeholder": {
            "type": "plain_text",
            "text": "Select a date"
          }
        },
        "label": {
          "type": "plain_text",
          "text": "Start date"
        }
      },
      {
        "type": "input",
        "block_id": "end_date",
        "element": {
          "type": "datepicker",
          "placeholder": {
            "type": "plain_text",
            "text": "Select a date"
          }
        },
        "label": {
          "type": "plain_text",
          "text": "End date"
        }
      }
    ]
  }
}
`

**Comment by H4zze** [comment]
Set rules modal code:
```
{
	"type": "modal",
	"title": {
		"type": "plain_text",
		"text": "New Season",
		"emoji": true
	},
	"submit": {
		"type": "plain_text",
		"text": "Save",
		"emoji": true
	},
	"close": {
		"type": "plain_text",
		"text": "Cancel",
		"emoji": true
	},
	"blocks": [
		{
			"type": "section",
			"text": {
				"type": "plain_text",
				"text": "Rules to be applied for new season",
				"emoji": true
			}
		},
		{
			"type": "divider"
		},
		{
			"type": "section",
			"text": {
				"type": "mrkdwn",
				"text": "*Select rules*"
			},
			"accessory": {
				"type": "checkboxes",
				"options": [
					{
						"text": {
							"type": "mrkdwn",
							"text": "*Tackle*"
						},
						"description": {
							"type": "mrkdwn",
							"text": "Bots can tackle eachother."
						},
						"value": "value-0"
					},
					{
						"text": {
							"type": "mrkdwn",
							"text": "*Teleporters*"
						},
						"description": {
							"type": "mrkdwn",
							"text": "The multi-colored discs are rendered on the board that teleport bots."
						},
						"value": "value-1"
					},
					{
						"text": {
							"type": "mrkdwn",
							"text": "*Red button / Diamond button*"
						},
						"description": {
							"type": "mrkdwn",
							"text": "Button to trigger a regeneration of all diamonds on the board."
						},
						"value": "value-2"
					}
				],
				"action_id": "checkboxes-action"
			}
		}
	]
}
```

**Comment by indrif** [comment]
Nice idea! Yeah we talked a bit about storing the rules in the db so it could be changed without deploying new code. And storing it per season would be a great way of doing it since we would be able to track the rules that were active each season in an easier way
