### ISSUE TITLE
Using imports relative project root makes production run break

### ISSUE THREAD

**Issue by R0tenur** [Etimo/diamonds2#23]
When the files are moved the import paths not working if it´s imported relative project root.

Breaks:
```
import { IPosition } from "src/common/interfaces/position.interface";
```
Works:
```
import { IPosition } from "../common/interfaces/position.interface";
```

**Comment by indrif** [comment]
Are imports still there in a production build?

Also can we use new tsconfig paths directive?

Example:
```
{
  "compileOnSave": false,
  "compilerOptions": {
    ...
    "paths": {
      "@root/*": ["src/*"],
    }
  }
}
```

**Comment by indrif** [comment]
Generally it will be problematic to have relative imports since things will break if and when things are refactored.

**Comment by ljukas** [comment]
See this: [Link](https://dev.to/cooperdev/restructure-with-ease-thanks-to-typescript-path-mappings-4b0e)

Dont forget to set the baseUrl in your tsconfig if you use the paths.
