### ISSUE TITLE
Rules & Highscore request for current season fails

### ISSUE THREAD

**Issue by H4zze** [Etimo/diamonds2#242]
Requesting rules and highscore for the current season when swapping current board return HTTP 500 due to the selected board being undefined.

![image](https://user-images.githubusercontent.com/21332068/168545739-a3875342-d496-42a8-9f2f-d646526517d3.png)

**Comment by indrif** [comment]
Don't know if still relevant for new frontend but please verify and close this otherwise

**Comment by wadholm** [comment]
I can't reproduce this issue, it might not have been relevant for the new frontend. 
Closing issue.

**Comment by wadholm** [comment]
I can't reproduce this issue, it might not have been relevant for the new frontend.
Closing issue.

**Comment by wadholm** [comment]
Error displayed in the Games view.
