### ISSUE TITLE
Seasons and Highscores

### ISSUE THREAD

**Issue by ljukas** [Etimo/diamonds2#89]
Instead of showing all previous highscores in an all-time list sorted by the amount of diamonds, they could be split up into their individual seasons. They could also not show the amount of diamonds collected, instead just showing them in the correct order, and maybe only show the top 5 contestants. This would not scare away new people when they see very high scores from seasons that were very different than the one currently running.

**Comment by ForsbergPhilip** [comment]
Added seasons and highscores.
