### ISSUE TITLE
UI not that responsive.

### ISSUE THREAD

**Issue by R0tenur** [Etimo/diamonds2#90]
Game board takes to much vertical space on phones.

![Screenshot_20200501-153748_Firefox](https://user-images.githubusercontent.com/12293736/80809439-f85cc600-8bc1-11ea-8498-58ded6c489f2.jpg)

**Comment by R0tenur** [comment]
Also the header days Etimo Etimo diamonds

**Comment by indrif** [comment]
![3029B9F6-CE38-460B-B529-15A9444BE45C](https://user-images.githubusercontent.com/6198331/80818687-f7349480-8bd3-11ea-9552-b1f774da609d.png)
Weird. Looks like this on iPhone.

**Comment by R0tenur** [comment]
I looked a second time, looked fine in Chrome. My Firefox om Android may be an odd combo :see_no_evil:

**Comment by ljukas** [comment]
I still want to take another look at the UI. I am better att css and styling overall than I was when I rewrote the frontend. When I have time I want to fix certain things, like on very wide screens, such as mine, the board becomes to big because it isnt locked to any width etc.
