### ISSUE TITLE
Slow bot movement

### ISSUE THREAD

**Issue by twmanar** [Etimo/diamonds2#93]
It seems like bot movement is slowed down when multiple bots are in play on all boards. The more bots, the slower the movement.

**Comment by twmanar** [comment]
After some small testing it looks like a request could take up to 0.7s in the worst case. The slowdown seem at times to be random.

**Comment by indrif** [comment]
Thanks for reporting. We are aware of the issue and are looking into it.

**Comment by indrif** [comment]
Hi! We have made some changes to the machine, please feel free to try again and see how it works out for you.
